# Generated by Django 4.0.5 on 2022-06-20 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.DecimalField(decimal_places=0, max_digits=16)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=30, null=True)),
                ('value', models.DecimalField(decimal_places=12, max_digits=16)),
                ('oneday_view_cost', models.DecimalField(decimal_places=12, max_digits=16)),
                ('oneday_click_cost', models.DecimalField(decimal_places=12, max_digits=16)),
                ('cmpaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook_api.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignReach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=30, null=True)),
                ('value', models.DecimalField(decimal_places=0, max_digits=8)),
                ('oneday_view', models.DecimalField(decimal_places=0, max_digits=8)),
                ('oneday_click', models.DecimalField(decimal_places=0, max_digits=8)),
                ('cmpaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook_api.campaign')),
            ],
        ),
    ]
